### ISSUE TITLE
寻找 slick update 的 where 代码块

### ISSUE THREAD

**Issue by djx314** [djx314/test01#1]
@tminglei
涂总你好，目前我在填 slick 的 497 号这个坑，打算作为第三方库支持的形式搞。我想问问 slick-pg 有没有做过怎么用字符串拼接 update 时候的那个 where 条件的（就是 filter）？因为我也打算用字符串拼接的方式搞。
而且老实说，这不是 slick 能解决的问题，必须借助一些外部的库和一些不同的思路。

还有也想问问除了 filter 之外还有没有其他地方需要到类似的额外字符串拼接的？对 sql 不是很熟悉很熟悉。先谢谢涂总啦 :-)

(不好意思，刚不小心把 issue 引到 slick 那里去了，在这里重开一个)

**Comment by tminglei** [comment]
没做过，slick-pg 这边只做过 函数相关的字符串生成，在 `ExPostgresProfile.scala`。

**Comment by djx314** [comment]
@tminglei 好滴，我去看看，还是谢谢啦

**Comment by tminglei** [comment]
不客气^^
